
auth.jdbcUrl=jdbc:mariadb://localhost:3306/auth_db?allowPublicKeyRetrieval=true&useSSL=false
auth.username=root
auth.password=#Your_sql_Password

erp.jdbcUrl=jdbc:mariadb://localhost:3306/erp_db?allowPublicKeyRetrieval=true&useSSL=false
erp.username=root
erp.password=#Your_sql_Password
